package formdb;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.DOMException;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

public class Window extends javax.swing.JFrame {
    
    private File file;
    private ArrayList<String> tableNames;
    private final String strNewTable = "New...";
    private final String configFile = "dbCredentials.xml";
    private SQL sql;

    public Window() {
        initComponents();
        try {
            //Get credentials from XML file
            Document doc = readXMLFile (configFile);
            
            //Establish SQL connection
            String user = doc.getElementsByTagName("user").item(0).getTextContent();
            String password = doc.getElementsByTagName("password").item(0).getTextContent();
            System.out.println(user);
            System.out.println(password);
            this.sql = new SQL (user, password, "Forms");
        }
        catch (DOMException | SQLException ex) {
            //Exit if failed
            System.out.println(ex.getMessage());
            System.exit(-1);
        }
        this.tableNames = this.sql.getTables();
        this.updateTableNames();
    }
    
    //Read XML file
    private Document readXMLFile(String fName) {
        try {
            File xmlFile = new File(fName);
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(xmlFile);
            
            return doc;
        }
        catch (IOException | ParserConfigurationException | SAXException ex) {
            System.out.println(ex.getMessage());
            
            return null;
        }
    }
    
    //Updates combobox with all tables found in the database
    private void updateTableNames () {
        this.cbTableName.removeAllItems();
        for (String tableName : this.tableNames) {
            this.cbTableName.addItem(tableName);
        }
        this.cbTableName.addItem(this.strNewTable);
    }
    
    //Get path of selected file
    public String getPath(){
        return this.file.getAbsolutePath();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lFormDir = new javax.swing.JLabel();
        txtDirectory = new javax.swing.JTextField();
        bBrowse = new javax.swing.JButton();
        bSubmit = new javax.swing.JButton();
        lTableName = new javax.swing.JLabel();
        cbTableName = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Database");

        lFormDir.setText("Form Directory");

        txtDirectory.setEditable(false);

        bBrowse.setText("Browse");
        bBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowseActionPerformed(evt);
            }
        });

        bSubmit.setText("Submit");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        lTableName.setText("Table Name");

        cbTableName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lTableName)
                    .addComponent(lFormDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addComponent(cbTableName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFormDir)
                    .addComponent(txtDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTableName)
                    .addComponent(cbTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSubmit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBrowseActionPerformed

        //File chooser for PDF files only
        JFileChooser chooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("PDF Document", new String[] {"pdf"});
        chooser.setFileFilter (filter);
        chooser.addChoosableFileFilter(filter);
        int result = chooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            this.file = chooser.getSelectedFile();
            this.txtDirectory.setText(this.getPath());
        }
    }//GEN-LAST:event_bBrowseActionPerformed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed

        String tableName = (String) this.cbTableName.getSelectedItem();
        
        //Create a new table
        if (tableName.equals(this.strNewTable)) {
            tableName = JOptionPane.showInputDialog("Enter new table name:");
            String cmd = SQL.createCommand(tableName, this.getPath()); //Check for duplicate?
            try {
                this.sql.execute(cmd);
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Table creation Failed!");
            }
            finally {
                this.updateTableNames();
            }         
        }
        
        //Insert data into correct table
        String cmd = SQL.insertCommand(tableName, this.getPath());
        try {
            this.sql.execute(cmd);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Submition Failed!");
        }
        JOptionPane.showMessageDialog(this, "Form submitted!");
    }//GEN-LAST:event_bSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBrowse;
    private javax.swing.JButton bSubmit;
    private javax.swing.JComboBox cbTableName;
    private javax.swing.JLabel lFormDir;
    private javax.swing.JLabel lTableName;
    private javax.swing.JTextField txtDirectory;
    // End of variables declaration//GEN-END:variables
}
